# [tools] - 开发工具版本
[tools]
python = "latest"

# [env] - 环境变量
[env]
_.path = ["C:\\msys64\\clang64\\bin"]

# [tasks] - 项目任务

[tasks.watch]
description = "Watch C source structure"
run = "python tools/watch_sources.py"

