#ifndef CALCULATOR_EXPECTED_H
#define CALCULATOR_EXPECTED_H

#define EXPECTED_ADD 17
#define EXPECTED_SUBTRACT 7
#define EXPECTED_MULTIPLY 60
#define EXPECTED_DIVIDE 2
#define EXPECTED_REMAINDER 2

#endif
